#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

echo "Changing directory to 'blog'..."

cd blog

echo "Checking commit convention..."

npm run commit:check

echo "Typechecking..."

npm run typecheck

echo "Runnig linting and fix..."

npm run lint:fix

git add .
